### PR TITLE
Add Hackage support!

### PR DESCRIPTION
**Pull request by relrod**
This adds version badge support for Haskell's Hackage. :)

It is heavily based on how the "gem" one works.

### CODE REVIEW

**Comment by espadrine** [comment]
Excellent!

**Comment by relrod** [comment]
Any idea when this'll be live? Would love to start using it. :)

**Comment by relrod** [comment]
Ah, nevermind. It is on http://img.shields.io/ but not http://b.adge.me/ - Oops!

**Comment by espadrine** [comment]
Yep, `b.adge.me` purposefully lags behind. You should use `img.shields.io` as much as possible.

**Pull request merged**
